#!/usr/bin/env python3
"""Build the Studia Islamika manuscript (.docx): 9,000+ words, APSA in-text
citations, 47-entry bibliography, 150-word abstract, five keywords, 12pt,
em-dashes purged (avoid-ai-writing). Figures and tables embedded in-text.
python-docx build; verified references (DOIs/links checked via web search)."""
import os, re
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIG = os.path.join(ROOT, "data", "out", "figs")
OUT = os.path.join(ROOT, "manuscript", "Draft_ConvergentScripture_DivergentRulings.docx")

doc = Document()
st = doc.styles["Normal"]; st.font.name = "Times New Roman"; st.font.size = Pt(12)
st.paragraph_format.line_spacing = 1.0

def h1(t):
    doc.add_heading(t, level=1)
def h2(t):
    doc.add_heading(t, level=2)
def para(t, italic=False, align=None, size=12, indent=True):
    p = doc.add_paragraph(); r = p.add_run(t); r.italic = italic; r.font.size = Pt(size)
    if align == "c":
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    else:
        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        if indent: p.paragraph_format.first_line_indent = Inches(0.4)
    p.paragraph_format.space_after = Pt(6); p.paragraph_format.line_spacing = 1.0
    return p
def figure(fname, caption, width=6.0):
    path = os.path.join(FIG, fname)
    if os.path.exists(path):
        doc.add_picture(path, width=Inches(width))
        doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
    c = doc.add_paragraph(); r = c.add_run(caption); r.italic = True; r.font.size = Pt(10)
    c.alignment = WD_ALIGN_PARAGRAPH.CENTER; c.paragraph_format.space_after = Pt(10)
def table(headers, rows, caption=None):
    if caption:
        cp = doc.add_paragraph(); r = cp.add_run(caption); r.italic = True; r.font.size = Pt(10)
    t = doc.add_table(rows=1, cols=len(headers)); t.style = "Light Grid Accent 1"
    for i, hd in enumerate(headers):
        run = t.rows[0].cells[i].paragraphs[0].add_run(hd); run.bold = True; run.font.size = Pt(10)
    for row in rows:
        cells = t.add_row().cells
        for i, val in enumerate(row):
            run = cells[i].paragraphs[0].add_run(str(val)); run.font.size = Pt(10)
    doc.add_paragraph().paragraph_format.space_after = Pt(6)

def para_ar(t, size=11, bold=False):
    p = doc.add_paragraph(); p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    pPr = p._p.get_or_add_pPr(); pPr.append(OxmlElement("w:bidi"))
    r = p.add_run(t); r.bold = bold; r.font.size = Pt(size); r.font.name = "Times New Roman"
    rPr = r._r.get_or_add_rPr()
    rtl = OxmlElement("w:rtl"); rtl.set(qn("w:val"), "1"); rPr.append(rtl)
    rf = rPr.find(qn("w:rFonts"))
    if rf is None: rf = OxmlElement("w:rFonts"); rPr.insert(0, rf)
    rf.set(qn("w:cs"), "Times New Roman")
    szcs = OxmlElement("w:szCs"); szcs.set(qn("w:val"), str(int(size*2))); rPr.append(szcs)
    p.paragraph_format.space_after = Pt(6); p.paragraph_format.line_spacing = 1.0
    return p

# ============================ FRONT MATTER ============================
tt = doc.add_heading("", level=0)
_tr = tt.add_run("Convergent Scripture, Divergent Rulings: Qurʾān Translation and Muʿāmalāt Fatwa across Southeast Asia")
_tr.font.size = Pt(16)
para("[Author name and affiliation withheld for blind review]", italic=True, align="c")

h2("Abstract")
para("Rendering the Qurʾān into a vernacular is, across Southeast Asia, a work of the state. Indonesia, Malaysia, and Brunei each stand behind an official edition read by millions, and their neighbours rely on closely related texts. It asks how those editions render the muʿāmalāt (commercial-ethics) verses and whether their choices track each state's fatwa posture on the economy. Transposing the text-mining method of Lange et al. (2021) from classical Arabic to a multilingual Southeast Asian corpus, it compares fifty-six anchor verses across five editions using language-agnostic sentence embeddings and close reading. Translation is a layer of convergence: similarity is governed by language family, and the Malay editions of Malaysia and Brunei are the most similar pair. Fatwa is the layer of divergence: on interest, insurance, cryptocurrency, and tawarruq the same states run from most to least permissive as Malaysia, Singapore, Brunei, and Indonesia, an ordering their translations do not predict.", size=11, indent=False)
para("Keywords: Qurʾān translation; Southeast Asia; muʿāmalāt; fatwa; political economy", italic=True, size=11, indent=False)
para_ar("الملخص", size=12, bold=True)
para_ar("يُعَدُّ نقلُ معاني القرآن الكريم إلى اللغات المحلية في جنوب شرق آسيا عملاً تقوم به الدولة؛ فإندونيسيا وماليزيا وبروناي تقف كلٌّ منها وراء ترجمةٍ رسميةٍ يقرؤها الملايين، وتعتمد الدول المجاورة على نصوصٍ وثيقةِ الصلة بها. تتساءل هذه الدراسة عن كيفية ترجمة هذه الطبعات لآيات المعاملات (أخلاقيات المال والاقتصاد)، وعمّا إذا كانت خياراتُها تتوافق مع موقف كلِّ دولةٍ الفقهيِّ (الفتوى) تجاه الاقتصاد. وبنقلِ منهج التنقيب في النصوص عند لانغه وزملائه (2021) من العربية الكلاسيكية إلى مدوّنةٍ متعددة اللغات في جنوب شرق آسيا، تقارن الدراسة ستّاً وخمسين آيةً مرجعيةً عبر خمس طبعاتٍ باستخدام التضميناتِ الجُمليّة العابرة للّغات والقراءةِ المتأنّية. فالترجمة طبقةُ تقاربٍ؛ إذ يحكم التشابهَ الانتماءُ اللغويُّ، وتُعدّ الطبعتان الملايويّتان لماليزيا وبروناي أكثرَ الأزواج تشابهاً. أمّا الفتوى فطبقةُ تباعدٍ؛ ففي الفائدة والتأمين والعملات المشفَّرة والتورُّق تتدرّج الدولُ نفسُها من الأكثر تساهلاً إلى الأكثر تشدداً على النحو: ماليزيا، فسنغافورة، فبروناي، فإندونيسيا؛ وهو ترتيبٌ لا تتنبّأ به ترجماتُها.", size=11)
para_ar("الكلمات المفتاحية: ترجمة القرآن؛ جنوب شرق آسيا؛ المعاملات؛ الفتوى؛ الاقتصاد السياسي", size=11)

# ============================ 1. INTRODUCTION ============================
h1("1. Introduction")
para("In Southeast Asia, rendering the Qurʾān into a vernacular is rarely a private undertaking. Indonesia's Ministry of Religious Affairs, Malaysia's Department of Islamic Development (JAKIM), Brunei's Islamic Daʿwah Centre, and their counterparts in Thailand and the Philippines each stand behind an official or semi-official edition. These editions circulate in mosques, in schools, and increasingly in mobile applications used by millions of readers. They are the everyday interface between scripture and the public. For most Southeast Asian Muslims, the meaning of a verse is the meaning their national edition gives it.")
para("Among the verses that carry the heaviest practical weight are those touching muʿāmalāt, the domain of commercial and economic conduct: the prohibition of ribā, the condemnation of fraudulent measures, and the ethics of contracts, debt, trusteeship, and inheritance. These verses underwrite a fast-growing Islamic-finance sector (Warde 2010; El-Gamal 2006), shape zakat administration, and inform public argument about fairness in the marketplace. How a national edition renders “those who give short measure” or “God has permitted trade and forbidden ribā” is therefore not a narrow philological matter. It is a small but consequential act of economic meaning-making, repeated across a region of unusual religious, linguistic, and institutional diversity.")
para("The stakes are not only interpretive. Islamic banking assets in the region are counted in the hundreds of billions of dollars, and the rulings that define what counts as compliant finance are issued by the same religious authorities that stand behind the translations (Warde 2010; Rudnyckyj 2019). To ask how those authorities render the economic Qurʾān, and how they rule on the economy, is to ask about the scriptural and institutional foundations of a major sector, and about who in each state gets to decide what the sacred text permits.")
para("Scholarship on Qurʾānic interpretation in the Malay-Indonesian world is deep but overwhelmingly qualitative. Studies of the transmission of learning (Azra 2004; Riddell 2001), of the exegetical tradition (Johns 1988), and of contemporary interpretation and its media (Pink 2019; Wilson 2014) have mapped the field in detail. What this literature has not done is measure, across many verses and several national editions at once, where Southeast Asian renderings of economic scripture agree and where they part ways. The reason is partly methodological. Close reading, the discipline's native mode, does not scale to systematic cross-edition comparison. The digital humanities offer one response through what Moretti (2013) called distant reading, and computational method has begun to enter Islamic studies (Muhanna 2016). Lange et al. (2021) show, on a large classical-Arabic corpus of substantive law, that text mining can confirm, qualify, and sometimes correct received claims about Islamic legal literature. Their toolkit has not yet been turned on the modern, multilingual, vernacular Qurʾān of Southeast Asia.")
para("This article does that, and it does not stop at the text. It replicates the analytical repertoire of Lange et al. (2021), namely frequency analysis, similarity networks, and distinctive-vocabulary clouds, and transposes it from a mono-lingual, diachronic Arabic corpus to a multilingual, synchronic Southeast Asian one. The transposition is not mechanical. Because every national edition renders the same Arabic source, Lange's central instrument, text-reuse detection, becomes uninformative: at the level of the verse, reuse is total. What matters instead is divergence in how the shared source is rendered. We replace text-reuse with cross-edition semantic similarity, computed with a language-agnostic sentence-embedding model (LaBSE) that places renderings in five languages into one comparable vector space (Feng et al. 2022; Reimers and Gurevych 2019). Anchoring on the invariant Arabic text, we assemble fifty-six muʿāmalāt verses across fifteen thematic domains and compare five national editions (Indonesia, Malaysia, Brunei, Thailand, and the Philippines). All texts are drawn as clean digital data from open repositories, so that no optical-character-recognition error enters the analysis.")
para("Three preliminary findings frame the study. First, similarity between editions is governed above all by language family. The three Malay-language editions of Indonesia, Malaysia, and Brunei cluster tightly, and within that cluster Malaysia and Brunei, two different states, form the most similar pair in the whole matrix (mean cosine 0.93). A paired test confirms that this closeness is not an artefact of chance. The result carries a lesson we hold throughout: cross-lingual scores measure linguistic distance as much as interpretive distance, so genuine differences of understanding must be read within the cognate editions and through close reading. Second, divergence is not uniform: it is higher for verses on measures and on contracts than for inheritance, which suggests that some economic-ethical concepts admit more interpretive latitude than others. Third, close reading of the single most divergent verse, “Woe to those who give short measure” (Q 83:1), shows the Tagalog edition generalizing a specifically commercial sin into ordinary petty theft while the other editions keep the verse anchored to the marketplace.")
para("We then set this textual convergence against a second layer. Where the translations barely differ, the states' muʿāmalāt fatwas diverge sharply. On bank interest, insurance, cryptocurrency, and tawarruq, the same states run from most to least permissive as Malaysia, Singapore, Brunei, and Indonesia. Their translations would not predict this ordering, since Malaysia and Brunei are the closest pair on the textual layer yet sit at opposite fatwa poles. We read Qurʾān translation in Southeast Asia as a layer of convergence, a shared and conservative scriptural substrate, and fatwa as the layer where that substrate meets divergent national conditions (Hooker 2003; Rudnyckyj 2019). We are cautious about the causal reach of the claim. With five editions and four issues it is a patterned, illustrative association rather than a tested correlation, and part of the divergence reflects a difference of genre, since translation answers to the text and fatwa to circumstance. Our narrower contribution is that the direction of fatwa divergence tracks each state's economic-institutional position in a way genre alone would not predict.")
para("The article proceeds as follows. Section 2 situates the study between digital humanities, Qurʾān translation in the Malay-Indonesian world, translation theory, and the political economy of Islamic law. Section 3 describes the corpus and the transposed method. Section 4 reports the convergence of the translation layer, and Section 5 turns to domain-dependent divergence and close reading. Section 6 compares the states' muʿāmalāt fatwa regimes and develops the contrast between translation convergence and fatwa divergence. Section 7 discusses the pattern, Section 8 states limitations, and Section 9 concludes.")

# ============================ 2. FRAMEWORK ============================
h1("2. Distant reading, Qurʾān translation, and the political economy of muʿāmalāt")
h2("2.1 Computational method in Islamic studies")
para("Distant reading, in Moretti's (2013) sense, trades the close analysis of single texts for the detection of patterns across many. In literary studies the approach matured through corpus-scale work on genre and style (Jockers 2013; Underwood 2019). Its arrival in Islamic and Middle Eastern studies was signalled by Muhanna (2016), and its most sustained demonstration for Islamic law is Lange et al. (2021), who mined a fifty-five-book corpus of furūʿ al-fiqh to study the role of the Qurʾān, the distribution of normative qualifications, and the thematic structure of the tradition. The computational apparatus we use descends from a specific line of natural-language-processing research: contextual embeddings from transformer models (Devlin et al. 2019), their extension to whole sentences (Reimers and Gurevych 2019), and the cross-lingual variant that anchors this study (Feng et al. 2022). Where topic structure is discussed we follow the standard generative account of latent topics (Blei, Ng, and Jordan 2003) and its recent embedding-based successors (Grootendorst 2022). We borrow this repertoire but invert its object. Where Lange et al. (2021) read one language across a millennium, we read one moment across five languages, holding the Arabic source constant.")
para("The method has a built-in modesty. Distant reading does not interpret; it locates. It can tell us that two renderings are far apart in meaning-space and can rank verses by how much the editions disagree, but it cannot say why they disagree or what the disagreement means. That work belongs to close reading, and the two must be used together, as Lange et al. (2021) themselves insist. The embeddings are best understood as a finding aid at scale: they point to the verses and the pairs worth reading closely, and they establish, quantitatively, the baseline of convergence against which any particular divergence must be judged.")
h2("2.2 Qurʾān translation and exegesis in the Malay-Indonesian world")
para("Qurʾānic learning in the archipelago was shaped by centuries of exchange with the wider Muslim world (Azra 2004), and Malay exegesis developed its own genres and emphases (Johns 1988; Riddell 2001). The modern moment adds two forces that this article measures. One is the nation-state, which turned translation into an instrument of religious governance, a process visible across the Muslim world from Turkey (Wilson 2014) to Indonesia. The other is the tension Pink (2019) foregrounds between globalizing standards and localizing communities, and the role of state and media in deciding which reading becomes authoritative. Vernacular translation is where that tension is resolved verse by verse, and it is precisely this layer, rather than the classical Arabic commentary, that most Muslims in the region actually read.")
para("Focusing on muʿāmalāt rather than on ritual or creedal verses is a deliberate choice. Commercial ethics is where scripture meets a live, contested, and heavily institutionalized domain of modern life, and where the gap between what a text says and what an authority rules is most consequential. Verses on prayer or belief rarely provoke the kind of national divergence in ruling that verses on interest and exchange do, precisely because they are less entangled with the state's economic apparatus.")
h2("2.3 Translation as localization")
para("Translation theory sharpens what we observe. Nida's (1964) account of dynamic equivalence and Baker's (2018) analysis of choice at the level of the word give the mechanics; Venuti's (2008) distinction between domesticating and foreignizing strategies gives the politics. To domesticate is to fit a text to the receiving culture's idiom, to foreignize is to preserve its strangeness, and the choice is, in Venuti's argument, an ethical and cultural act rather than a neutral one. When the Tagalog edition renders a Qurʾānic term for fraudulent measurement as ordinary pilfering, and drops the commercial gloss that the other editions keep, it domesticates a market-specific sin into a general one. Localization, in this vocabulary, is not a metaphor. It is a describable translational operation with measurable traces, and Section 5 measures them.")
h2("2.4 The political economy of Islamic finance and fatwa")
para("The religious authorities that rule on the economy are institutions embedded in national economic projects. Kuran (2004) reads much of modern Islamic economics as an identity project rather than a distinct economic system, while El-Gamal (2006) shows how the sector's contracts are engineered around, rather than away from, conventional finance. Rethel (2011) argues that Islamic finance has largely reproduced the global financial order it set out to reform. Against this background Rudnyckyj's (2019) ethnography of Malaysia's ambition to become a global hub of Islamic finance is decisive for our reading: it shows how jurisprudence, regulation, and developmental strategy are entangled, and how Malaysian authorities have legitimized instruments, above all tawarruq and bai al-ʿīnah, that more cautious jurisdictions reject. This is the frame we bring to the fatwa layer.")
h2("2.5 Fatwa and religious authority")
para("A fatwa is a scholarly opinion whose force depends on the authority of the mufti and the institution behind it (Masud, Messick, and Powers 1996). In Indonesia that institution is the semi-autonomous Council of Indonesian Ulama, whose fatwa production has been studied both as legal reasoning (Hosen 2004) and as a barometer of a broader conservative turn (van Bruinessen 2013; Hooker 2003). The contrast with Malaysia, where finance rulings issue from a Shariah Advisory Council inside the central bank, is not merely doctrinal but institutional, and it maps onto the broader story of Islamic law and the state in the region (Feener 2013; Hallaq 2009). The analytical payoff of combining these literatures is a two-layer design: a computational, cross-lingual measurement of the translation layer, set against a coded, comparative reading of the fatwa layer, with translation theory and political economy supplying the interpretive lenses.")
para("Indonesia complicates any talk of a single national fatwa. Alongside the state-linked Council of Indonesian Ulama sit the deliberative bodies of the mass organizations, the Bahtsul Masail of Nahdlatul Ulama and the Majelis Tarjih of Muhammadiyah, which sometimes reach different conclusions on economic questions. We focus on the Council and its National Sharia Council because these are the bodies with statutory reach into the regulated Islamic-finance sector, and because they are the closest institutional analogue to the state translation authority. The plurality is real, and a fuller account would code it, but it does not disturb the cross-national comparison, which sets each state's most authoritative economic-fatwa body against the others.")
para("Southeast Asia is an unusually informative setting for a two-layer inquiry of this kind. Within a single region it holds Muslim-majority states of very different political form: a large electoral democracy in Indonesia, a federal constitutional monarchy with an explicit developmental-finance agenda in Malaysia, and an absolute Islamic monarchy in Brunei. Alongside them sit Muslim-minority polities, including Singapore and the Muslim regions of Thailand and the Philippines. These states share a scriptural tradition and, in the Malay-speaking core, a language, yet they have built markedly different economic-religious institutions (Salim 2008; Feener 2013; Ricklefs 2001). If translation and fatwa were merely two expressions of one underlying doctrine, they would be expected to co-vary. The interest of the region is that they do not. By holding scripture and, in the Malay core, language roughly constant, Southeast Asia isolates the institutional variable that the political economy of Islamic law has long asserted but rarely measured against the text itself.")
para("Three research questions follow. First, how convergent or divergent are Southeast Asian renderings of muʿāmalāt verses, and what governs the pattern? Second, which muʿāmalāt domains are most uniform and which most contested across editions? Third, how do the states' muʿāmalāt fatwa regimes compare, and does the ordering of their divergence align with independently describable economic-institutional positions rather than with anything in their translations?")

# ============================ 3. CORPUS AND METHODS ============================
h1("3. Corpus and methods")
para("Corpus construction. Following the selection logic of Lange et al. (2021), namely comprehensiveness, salience, and availability, we built a corpus anchored not on books but on verses. Fifty-six anchor verses span fifteen muʿāmalāt domains: ribā (for example Q 2:275–279, 3:130, 30:39), sale and trade, contracts and oaths, trust (amāna), gharar and gambling, measures and scales (for example Q 55:9, 83:1–3, 17:35), hoarding, unlawful gain, the property of orphans, bequest, inheritance, spending ethics, lawful earning, and wealth distribution. Each verse is keyed by its sūra–āya number, which is identical across editions and so serves as the join, with the Arabic text as the invariant anchor.")
para("The verse list is thematically representative rather than exhaustive. Within each domain we selected the verses most often cited in Islamic-economics scholarship and in the fatwa literature on our four anchor issues, so that the textual and juridical layers could be joined at the same scriptural points. The domains are unequal in size, with ribā and measures richly represented and bequest and wealth-distribution thin, which reflects the uneven attention the Qurʾān itself gives them; Section 5 shows that this unevenness is informative. Because the anchor is the sūra–āya key, every analysis can be sliced by domain, edition, or verse without re-alignment.")
para("Editions and provenance. Five national editions were compared. The Indonesian text is the Ministry of Religious Affairs (Kemenag/LPMQ) translation (Kementerian Agama RI 2019); the Malay text is the Basmeih rendering that underlies Malaysia's national tafsir; the Thai and Tagalog texts are the Rowwad and King Fahd Complex editions; and the Brunei text is the official Mushaf Brunei Darussalam, produced by the state's religious apparatus and distributed through the government's Mushaf Brunei application. The Indonesian, Thai, and Tagalog texts were drawn from the QuranEnc repository; the Malay text from the Quran.com application-programming interface; and the Brunei text extracted directly from the official application's bundled data. All five are clean, machine-readable text. We note openly that this is a corpus of standardized editions, and that the Thai and Tagalog texts are not state-authored in the way the Indonesian, Malay, and Brunei texts are; Section 8 returns to this asymmetry.")
para("The corpus was assembled without optical character recognition, because OCR of Arabic, of Jawi, and of Thai script introduces systematic error that would contaminate the embeddings. Working only with clean, machine-readable text also keeps the pipeline reproducible, since the same sūra–āya keys retrieve the same strings on every run. Extracting the Brunei translation strings bundled in the official application raised no access barrier beyond ordinary use, and the resulting corpus contains only the fifty-six anchor verses rather than the complete text, which keeps the material within the bounds of scholarly citation.")
para("The four anchor issues that structure the fatwa layer were chosen because each maps onto a well-defined cluster of muʿāmalāt verses and because each has generated explicit rulings in more than one state. Bank interest anchors on the ribā verses (Q 2:275–279 and 3:130); insurance and cryptocurrency both engage the prohibition of gharar and maysir (Q 2:219 and 5:90); and tawarruq, though a contract rather than a Qurʾānic term, is argued from the general permission of sale and the prohibition of ribā (Q 2:275). Anchoring the juridical comparison to the same verses that anchor the textual comparison is what allows the two layers to be set side by side rather than merely juxtaposed.")
para("Measuring the translation layer. Each rendering was embedded with LaBSE, a model trained to place semantically equivalent sentences in different languages near one another in a shared vector space (Feng et al. 2022). Because Lange's text-reuse instrument is uninformative here, we replace it with cross-edition similarity: for each verse we compute the cosine similarity between every pair of editions' embeddings, then average across verses to obtain a pairwise similarity matrix. We bootstrap 95 per cent confidence intervals (10,000 resamples) for each pair's mean cosine. To test whether within-family similarity exceeds cross-family similarity we use a paired Wilcoxon signed-rank test, pairing by verse. To ask whether divergence differs by domain we compute, per verse, one minus the mean pairwise cosine, and apply a Kruskal-Wallis test across domains with at least three verses. Distinctive vocabulary per edition is summarized with tf-idf weighting, and the semantic structure of the corpus with a force-directed similarity network.")
para("A word on the instrument. LaBSE was trained on parallel corpora to make translation pairs near in vector space, which is the property we exploit: two renderings of the same verse should be close if they carry the same meaning and farther apart if they do not (Feng et al. 2022). The model is not tuned on Qurʾānic text, so absolute cosine values are read comparatively rather than as calibrated distances, and the analysis relies on relative contrasts. As a sanity check the model recovers the expected structure: same-language and cognate-language renderings are placed nearest one another, and each verse's five renderings are mutually nearer than they are to other verses, which indicates that the embeddings track verse identity rather than surface language alone.")
para("Coding the fatwa layer. To characterize each state's muʿāmalāt fatwa output we did not attempt to mine entire fatwa corpora, an undertaking of a different scale and, for several states, of doubtful data availability. Instead we held four contemporary issues constant, namely conventional bank interest, insurance, cryptocurrency, and tawarruq, and coded each state's ruling on a five-point strictness scale (1 most permissive, 5 strictest) and a small set of framing categories (moral or legalist; justice or harm; technical; accommodation by necessity). Each cell carries an evidence tier: fatwa (an explicit, located ruling), inference (coded from institutional or legal frameworks where no issue-specific fatwa was located), or advisory (a regulatory notice that is not a religious ruling). The codebook, the coded table, and the source dossier are provided as supplementary material, and a two-coder reliability check with Cohen's kappa is specified there. The pipeline is split for reproducibility: Python performs corpus assembly and natural-language processing and writes intermediate files, and R produces the figures, statistics, and tables.")

# ============================ 4. RESULTS I ============================
h1("4. Results I: the translation layer converges")
para("The cross-edition similarity matrix (Figure 1, Table 1) is dominated by one fact, which is language family. The three Malay-language editions of Indonesia, Malaysia, and Brunei form a tight cluster, and within it the two Malay-proper state editions, Malaysia (Basmeih) and Brunei (KHEU), are the most similar pair in the entire matrix (mean cosine 0.93). Indonesia sits close to both (0.91 with Brunei, 0.88 with Malaysia). The Thai and Tagalog editions are markedly more distant from the Malay trio and from each other, with the Thailand-Philippines pair the least similar of all (0.70).")
figure("fig1_similarity_heatmap.png", "Figure 1. Cross-edition similarity of muʿāmalāt renderings (LaBSE mean cosine). Darker indicates greater similarity.")
table(["Edition", "Indonesia", "Malaysia", "Thailand", "Philippines", "Brunei"],
      [["Indonesia","1.00","0.88","0.77","0.78","0.91"],
       ["Malaysia","0.88","1.00","0.78","0.76","0.93"],
       ["Thailand","0.77","0.78","1.00","0.70","0.79"],
       ["Philippines","0.78","0.76","0.70","1.00","0.76"],
       ["Brunei","0.91","0.93","0.79","0.76","1.00"]],
      caption="Table 1. Cross-edition similarity matrix (LaBSE mean cosine, 56 verses).")
para("Bootstrap confidence intervals (Figure 2) confirm that the clustering is not noise. The three Malay-family pairs occupy a band whose confidence intervals do not overlap any cross-family pair. A paired Wilcoxon signed-rank test, pairing by verse, finds within-Malay-family similarity significantly greater than cross-family similarity (V = 1596, p = 3.9 × 10⁻¹¹).")
figure("fig5_pair_ci_forest.png", "Figure 2. Cross-edition similarity with 95 per cent bootstrap confidence intervals. The three Malay-family pairs separate cleanly from all cross-family pairs.")
para("This result is, in one sense, unsurprising, since cognate languages produce cognate translations. That is the point. It tells us that cross-lingual similarity here measures linguistic distance at least as much as interpretive distance, and it warns against reading the low Thai and Tagalog scores as evidence of doctrinal difference. The informative comparisons are therefore two: divergence within the cognate Malay editions, where language is held roughly constant, and close reading of individual verses. Both are pursued below. The convergence result also does substantive work of its own. It establishes that, at the level of the text, Southeast Asia's state editions form a shared, conservative substrate, a baseline against which the divergence of the fatwa layer, reported in Section 6, becomes legible.")
para("The tight clustering of the three Malay editions deserves a further word. Indonesian and Malay are closely related languages, and the Brunei and Malaysian texts are both written in standard Malay, which explains why the Malaysia-Brunei pair is the closest of all. Yet the clustering is not merely a linguistic accident. All three editions descend from a shared tradition of Malay Qurʾānic rendering with centuries of common vocabulary and phrasing (Riddell 2001; Johns 1988), and all three are produced by state or state-adjacent bodies with an interest in a stable, authoritative text. The convergence is thus overdetermined, by language and by institutional conservatism alike, which makes the pockets of divergence identified in Section 5 all the more telling.")
para("An agglomerative clustering of the editions recovers the same structure: the three Malay editions join first, with Malaysia and Brunei merging at the lowest distance, then Indonesia, and only afterwards do the Thai and Tagalog editions attach at much greater distance. The dendrogram is, in effect, a family tree of renderings, and its shape is that of language history rather than doctrinal alignment. This is worth stating plainly because it disciplines every subsequent claim: whatever institutional divergence exists between these states, it does not show up as distance in the space of their translations.")

# ============================ 5. RESULTS II ============================
h1("5. Results II: domain-dependent divergence and a close reading")
para("Divergence is not spread evenly across the muʿāmalāt. Computing a per-verse divergence score and averaging within domains (Figure 3) shows the highest cross-edition spread in the domain of measures and scales, followed by contracts and oaths, lawful earning, and ribā; the lowest spread appears in inheritance and hoarding. A Kruskal-Wallis test across domains with at least three verses rejects the null of equal divergence (χ² = 20.3, df = 9, p = 0.016). The pattern is interpretable. Domains whose vocabulary is technical and repetitive, such as inheritance with its fixed fractional shares and kinship terms, leave translators little room to differ, whereas ethically abstract domains such as the justice of a fair measure or the fulfilment of a contract admit more latitude.")
figure("fig3_domain_divergence.png", "Figure 3. Cross-edition divergence by muʿāmalāt domain (1 minus mean cross-edition cosine).")
para("A frequency view of the corpus (Figure 4) confirms what dominates it lexically. Harta (wealth or property) is by far the most frequent content word, followed by a dense cluster of inheritance vocabulary (anak, laki, perempuan, saudara, bagian) and then by ribā, zakat, takaran and timbangan (measure and scale), and the ethics of exchange. The muʿāmalāt Qurʾān, in this corpus, is above all a scripture of wealth and its transfer, which is consistent with the reading of Islamic economics as centrally concerned with property and its just distribution (Kuran 2004).")
figure("fig8_wordcloud_themes.png", "Figure 4. Thematic vocabulary of the muʿāmalāt corpus (frequency; Indonesian edition; function words removed).")
para("A semantic network of the verses (Figure 5) makes the distribution of agreement visible. Most verses form a dense core of mutually similar renderings, and the verses that diverge most across editions, namely Q 83:1, Q 83:2, and Q 2:43, are pushed to the periphery as semantic outliers. Disagreement is concentrated in a few verses rather than spread thinly across the corpus.")
figure("fig6_verse_network.png", "Figure 5. Semantic network of muʿāmalāt verses. Nodes are verses, coloured by domain and sized by divergence; the most divergent verses sit at the periphery.")
para("The single most divergent verse rewards close reading. Q 83:1, wayl li-l-muṭaffifīn, opens Sūrat al-Muṭaffifīn with a threat against those who cheat in weighing and measuring. Table 2 sets the five renderings side by side. Three axes of divergence emerge. The threat word wayl is rendered in a strong eschatological register by the Indonesian, Malay, Thai, and Brunei editions (“woe”, “great calamity”, “catastrophe”) but softened by the Tagalog edition to kapighatian, “grief”. The sin, taṭfīf, is framed by the Indonesian and Malay editions as moral character (curang, “cheating”), by the Thai edition as a technical deficiency, and by the Tagalog edition as tagapag-umit-umit, “petty pilferers”, which generalizes a specifically commercial offence into ordinary theft. The commercial anchor, the parenthetical “in measuring and weighing”, is retained by four editions but dropped by the Tagalog. A verse about market honesty becomes, in the Tagalog rendering, a verse about pilfering. This is domestication in Venuti's (2008) sense, and it is measurable.")
table(["Edition", "Rendering of Q 83:1 (key terms)"],
      [["Indonesia (Kemenag)", "“Celakalah bagi orang-orang yang curang (dalam menakar dan menimbang)!” woe; cheats; measuring gloss retained"],
       ["Malaysia (Basmeih)", "“Kecelakaan besar bagi orang-orang yang curang (dalam timbangan dan sukatan)” great calamity; cheats; gloss retained"],
       ["Brunei (KHEU)", "“Celakalah bagi orang-orang yang menipu (dalam sukatan dan timbangan).” woe; deceive; gloss retained"],
       ["Thailand (Rowwad)", "catastrophe; “those who cause deficiency” in measuring and weighing; gloss retained, act nominalized"],
       ["Philippines (Tagalog)", "“Kapighatian ay ukol sa mga tagapag-umit-umit” grief; petty pilferers; no measuring gloss"]],
      caption="Table 2. Close reading of Q 83:1 across the five editions.")
para("Two points discipline the reading. First, the cognate Indonesian, Malay, and Brunei editions agree on all three axes, which, given the Wilcoxon result, indicates that the Tagalog divergence is a genuine translational choice rather than a language artefact. Second, the Tagalog text is a single Rowwad rendering, not a state edition, so its choices illustrate how localization can de-commercialize an economic verse in a minority-language context, and should not be read as the position of the Philippine state.")
para("A second verse confirms that the pattern is not confined to Q 83:1. Q 2:275 likens the one who consumes ribā to a person unable to stand except as one deranged by the touch of Satan. The Indonesian and Malay editions render the standing as a this-worldly inability to stand upright (tidak dapat berdiri), whereas the Brunei edition glosses it as an inability to rise from the grave on the Day of Resurrection (tidak akan dapat bangkit dari kubur). The two Malay-language state editions thus part company on whether the verse's image is worldly or eschatological, even as all five agree that ribā is forbidden. Here the divergence is genuinely interpretive rather than orthographic, and it appears, tellingly, within the cognate pair rather than across the language boundary.")
para("Beyond single verses, a distinctive-vocabulary analysis of the three Malay-language editions surfaces the texture of localization. A tf-idf comparison isolates the words each edition uses that the others do not: the Indonesian batil, bagian, takaran, and salat stand against the Malay and Brunei bathil, bahagian, sukatan, and sembahyang. Much of this is orthographic convention, the divergent Indonesian and Malay spelling traditions, but some is genuinely lexical, as when the Indonesian takaran meets the Malay-Brunei sukatan, or when Brunei renders the cheat of Q 83:1 as menipu where Malaysia writes curang. These are the fingerprints of three institutions rendering one text for three publics, and they confirm that the convergence reported in Section 4 is a convergence of meaning rather than of wording (Baker 2018).")
para("The orthographic layer is itself a marker of national religious identity. Indonesian spelling conventions (bagian, salat, batil) and Malay ones (bahagian, sembahyang, bathil) are standardized by different national bodies, and a reader can often tell at a glance which country's edition a page comes from without reading a word of content. This surface nationalization of a shared text is a small but real instance of how the state inscribes itself on scripture, even where it changes nothing of the meaning. It also means that any automated comparison must distinguish, as ours does through the semantic embedding, between differences of spelling and differences of sense.")

# ============================ 6. FATWA LAYER ============================
h1("6. The fatwa layer: translation convergence, fatwa divergence")
para("If the translations converge, the fatwas do not. Holding four contemporary issues constant, namely bank interest, insurance, cryptocurrency, and tawarruq, and coding each state's ruling on strictness and framing (Figure 6, Table 3), the states run from most to least permissive as Malaysia, Singapore, Brunei, and Indonesia. No feature of their translations predicts this ordering. On the textual layer Malaysia and Brunei are the most similar pair of all, yet on the fatwa layer they sit far apart.")
figure("fig9_fatwa_strictness.png", "Figure 6. Fatwa strictness on four muʿāmalāt issues, by state (1 most permissive, 5 strictest). An asterisk marks institutional inference; a double asterisk marks a regulatory advisory that is not a religious fatwa.")
table(["Issue", "Indonesia", "Malaysia", "Singapore", "Brunei"],
      [["Bank interest", "Blanket haram, ribā nasīʾa (5)", "Riba in principle; permits bai al-ʿīnah and tawarruq (3)", "Pragmatic tolerance by necessity (2)*", "Prohibited; institutionalized Islamic banking (5)*"],
       ["Insurance", "Conventional haram; build takaful (5)", "Takaful promoted (3)*", "Conventional permitted by necessity; CPF as hiba (1)", "Takaful Order 2008; conventional discouraged (4)*"],
       ["Crypto", "Haram unless asset-backed (4)", "Conditional; SC-licensed (2)", "Cautious; no blanket ruling (3)*", "BDCB advisory only; not a fatwa (4)**"],
       ["Tawarruq", "Restrictive; rejects bai al-ʿīnah (4)", "Permissible; Bursa Suq al-Sila (1)", "Follows industry (3)*", "Equity and risk-sharing emphasis (4)*"]],
      caption="Table 3. Coded muʿāmalāt fatwa positions by state and issue (strictness 1–5; evidence tier: * inference, ** advisory). Benchmark: OIC Fiqh Academy (2009) ruled organized tawarruq prohibited (5).")
para("The four regimes fall into a typology. Malaysia is the most permissive. Its finance-fatwa authority sits inside the central bank, in the Shariah Advisory Council of Bank Negara Malaysia, and its rulings institutionalize the instruments a globally competitive Islamic-finance industry depends on. Organized tawarruq, prohibited by the OIC International Islamic Fiqh Academy in 2009, is not merely tolerated but operationalized through Bursa Suq al-Sila. This is a technical, industry-enabling jurisprudence aligned with a developmental-state agenda (Rudnyckyj 2019; Rethel 2011), and it relies on exactly the contract engineering that El-Gamal (2006) describes.")
para("Malaysia's arrangement is unusual in placing binding religious authority over finance inside the central bank. The Shariah Advisory Council of Bank Negara Malaysia issues rulings that bind the courts on Islamic-finance matters, which gives the state's developmental priorities a direct channel into jurisprudence. The result is a body of rulings that has made Malaysia the most permissive of the four regimes on the instruments that drive industry growth, and that has drawn criticism from scholars who read the sector as reproducing conventional finance under new names (El-Gamal 2006; Rethel 2011). The contrast with Indonesia is therefore not one of piety but of institutional design: the same prohibition of ribā yields a permissive regime in Kuala Lumpur and a restrictive one in Jakarta, because the institutions that interpret it answer to different masters.")
para("Indonesia sits at the opposite pole. The National Sharia Council of the Council of Indonesian Ulama rules bank interest to be ribā nasīʾa and conventional insurance impermissible, treats cryptocurrency as unlawful unless asset-backed, and rejects the very engineered contracts on which Malaysia's system runs (Hosen 2004; Hooker 2003). Its response to a prohibited conventional finance is not accommodation but the construction of a parallel Sharia system, a stance consistent with the assertive, orthodoxy-defining role the Council has taken in the post-Suharto period (van Bruinessen 2013). Here jurisprudence is moral and legalist.")
para("The Indonesian case has a documented institutional history. The Council of Indonesian Ulama was established in 1975, and for its first decades it issued fatwas whose reasoning has been catalogued and analysed at length (Mudzhar 1993; Kaptein 2004). Its economic rulings gained practical force with the creation of the National Sharia Council in 1999, which brought fatwa production into direct contact with a regulated Islamic-banking sector. The Council's insistence on prohibiting bank interest outright, rather than accommodating it through engineered contracts, is thus not an isolated pronouncement but a consistent institutional posture, one that fits its broader self-positioning as a guardian of orthodoxy in a competitive religious field (van Bruinessen 2013; Hooker 2003).")
para("Singapore occupies a third position that strictness alone does not capture. As the authority for a Muslim-minority state, its fatwa committee has permitted recourse to conventional insurance and treated Central Provident Fund nominations as valid hiba, grounding these permissions not in doctrinal laxity but in necessity (ḍarūra), given the local unavailability of takaful. Brunei completes the typology with a conservative institutionalization of prohibition, anchored in its Islamic Banking Act and a dedicated Syariah Financial Supervisory Board; on cryptocurrency its response arrives as a prudential advisory from the monetary authority rather than a religious ruling, a distinction we retain rather than smooth over.")
para("Singapore's jurisprudence of necessity has a longer pedigree than the insurance rulings alone suggest. As the religious authority for a minority community embedded in a secular, market-driven state, its fatwa committee has repeatedly reasoned from ḍarūra and maṣlaḥa to permit participation in institutions, from the Central Provident Fund to conventional banking, that a majority-state jurist might simply prohibit. This is not laxity but a distinct juridical logic, calibrated to the absence of a full Islamic-finance infrastructure and to the practical needs of Muslims who cannot opt out of national economic institutions. It is the mirror image of Malaysia's logic. Where Malaysia bends jurisprudence to build an industry, Singapore bends it to let a minority live within someone else's.")
para("Brunei's conservatism is institutional as much as doctrinal. Since the 1990s the sultanate has built a comprehensively Islamized financial system, and authority over its Sharia dimension rests with a dedicated Syariah Financial Supervisory Board rather than with the State Mufti alone. Rulings issue within a monarchical order in which religion and state are formally fused under the state ideology of Melayu Islam Beraja, so that a permissive accommodation of conventional finance of the Malaysian kind has neither the industrial motive nor the institutional space to develop. Brunei thus reaches a strict outcome by a route different from Indonesia's: not the assertive orthodoxy of a mass organization in a plural religious field, but the settled conservatism of a small, wealthy, absolutist state.")
para("Cryptocurrency is the sharpest contemporary test, because it confronts every regime with the same novelty at the same moment. The responses diverge along the lines the typology predicts. Indonesia rules crypto unlawful as a currency and, as a traded asset, unlawful unless it is asset-backed and of determinable value, invoking gharar and the risk of harm. Malaysia's securities regulator brings crypto inside a licensing regime and treats some tokens as tradeable, a technical accommodation consistent with its industry posture. Singapore remains cautious without a blanket ruling, and Brunei's response is a monetary-authority advisory warning that crypto is neither legal tender nor regulated. The same Arabic verses on gharar underlie all four responses; the responses differ because the institutions do.")
para("Read across the four issues, the ordering of Malaysia, Singapore, Brunei, and Indonesia tracks features of each state that can be described without reading its fatwas at all: Malaysia's hub ambition, Singapore's minority market, Indonesia's mass-organizational legalism and preference for parallel institutions, and Brunei's monarchical institutionalization. This is the paper's central contrast. Qurʾān translation in Southeast Asia is a layer of convergence, a shared and conservative scriptural substrate; fatwa is the layer where that substrate is operationalized under national economic conditions, and where the region's real diversity lives. The translation under-determines the fatwa; national economic-institutional conditions are where the difference appears. We advance this as a patterned association, not a demonstrated cause.")
para("A skeptic will object that translation and fatwa are simply different genres, one bound to the text and the other to circumstance, so their divergence needs no political-economy explanation. We accept the genre difference as part of the story and claim only that the ordering of divergence aligns with independently describable institutional positions that genre alone does not predict. Genre explains why translation is uniform and fatwa responsive, but it is silent on why Malaysia sits at the permissive pole and Indonesia at the strict one. The divergence we code, moreover, is measured between fatwas, country to country, where genre is held constant, so genre difference cannot by itself explain it. In at least one regime the mechanism is stated outright: Singapore's fatwa committee grounds its permission of conventional insurance in the local unavailability of takaful, an economic-institutional condition named in the ruling itself. A fuller version of this argument should assemble that kind of textual evidence for each state.")
para("A note on institutional location sharpens the point. In Indonesia the translating body, the Ministry of Religious Affairs, and the fatwa body, the Council of Indonesian Ulama, are distinct, whereas in Singapore and Brunei the scriptural and juridical functions sit closer together. The gap between text and ruling is thus, in some states, also a gap between two arms of the religious apparatus.")
para("The framing categories add texture to the strictness ordering. Indonesia's rulings are predominantly moral and legalist, naming ribā, gharar, and maysir as categorical wrongs. Malaysia's are predominantly technical, concerned with whether a given contract structure meets formal criteria. Singapore's are framed by necessity, and Brunei's by a combination of moral prohibition and state institutionalization. Strictness and framing are related but not identical: Singapore is permissive and frames by necessity, whereas Malaysia is permissive and frames by technical compliance, and the difference between these two permissive logics is as important as the difference between permissive and strict. A one-dimensional scale would miss it, which is why the coding records both.")
h2("6.1 The juristic mechanism: same scripture, different uṣūl")
para("If the translations of the ribā verses converge, so does the states' reading of what those verses prohibit. No authority in our set disputes that ribā, gharar, and maysir are forbidden, or that Q 2:275–279 and Q 2:219 establish the prohibition. The divergence is downstream of the verse. It lives in uṣūl al-fiqh, the legal method by which a modern instrument is judged against an agreed prohibition, and three mechanisms account for most of it, each readable in the fatwas' own reasoning.")
para("The first and largest is the maxim-level dispute over whether contracts are judged by their form or their substance: al-ʿibra fī al-ʿuqūd li-l-maqāṣid wa-l-maʿānī (consideration is given to intentions and meanings) against al-ʿibra li-l-alfāẓ wa-l-mabānī (consideration is given to wordings and forms). The clearest test case is tawarruq and its cousin bayʿ al-ʿīnah. Malaysia's Shariah Advisory Council rules bayʿ al-ʿīnah permissible, and organized tawarruq permissible, provided the sale and purchase contracts run in the correct sequence, a formal-validity test in the classical Shāfiʿī manner of judging each contract by its outward form (Bank Negara Malaysia 2010). Indonesia's National Sharia Council reaches the opposite practical result from the same sources: its Fatwa 82/2011 permits tawarruq only by necessity (ḥājah) and requires genuine possession (qabḍ) before resale, citing the maxim mā addā ilā al-ḥarām fa-huwa ḥarām, which is sadd al-dharāʾiʿ, alongside lā ḍarar wa-lā ḍirār and darʾ al-mafāsid muqaddam ʿalā jalb al-maṣāliḥ, in line with international standards limiting tawarruq to necessity (DSN-MUI 2011; AAOIFI 2010; OIC Fiqh Academy 2009). Two councils that share a madhhab, a scripture, and much of the ḥadīth corpus thus split because one asks whether each contract is formally valid and the other whether the sequence is a stratagem (ḥīla) for a forbidden end. Form against substance, not verse against verse.")
para("The second mechanism is takyīf fiqhī, the classification of a novel instrument under an established category. On bank interest the councils do not disagree about the verses but about whether modern interest instantiates the ribā they prohibit. Indonesia's MUI answers that it does, classifying bank interest as ribā nasīʾah, an increase without countervalue arising from deferment, and forbidding it across banks, insurers, pawnbrokers, and cooperatives (MUI 2004). The same operation governs cryptocurrency, where the 2022 fatwa turns not on a new reading of any verse but on whether crypto is māl with lawful value as a medium of exchange and on the gharar it carries, ruling it unlawful as currency and unlawful as a traded asset unless asset-backed and of determinable value (MUI 2022).")
para("The third mechanism is the selective weighting of enabling principles, above all necessity. Singapore's fatwa committee does not read ribā or gharar differently from its neighbours; it permits recourse to conventional insurance by invoking ḍarūra and the maxim al-ḍarūrāt tubīḥ al-maḥẓūrāt, on the express ground that takaful is unavailable in the local market (MUIS 2010). The permission is generated by circumstance operating through a recognized principle, not by a softer reading of the prohibition.")
para("These three mechanisms explain how the fatwa layer can diverge so sharply while the translation layer barely moves. The states are not reading the Qurʾān differently; they are reasoning differently from a Qurʾān they read alike. The choice of which reasoning to privilege, formal validity or substantive purpose, industry-enabling maṣlaḥa or minority ḍarūra, is where each state's economic-institutional position enters. Malaysia's formalism serves an industry that needs workable instruments; Indonesia's substantivism serves a council that prefers to build a parallel system rather than engineer around the prohibition; Singapore's necessity serves a minority that cannot opt out. The mechanism is uṣūl al-fiqh; what selects among its tools is political economy (El-Gamal 2006; Rudnyckyj 2019).")

# ============================ 7. DISCUSSION ============================
h1("7. Discussion")
para("The two-layer pattern relocates where the interesting variation in Southeast Asian muʿāmalāt lives. It is not in how states translate scripture, since there they barely differ, but in how their fatwa institutions operationalize it under national economic conditions. This has a methodological implication for digital humanities in Islamic studies. On a corpus of standardized translations, cross-lingual text mining is best used not to hunt for doctrinal difference in the text, where little exists, but to establish a rigorous baseline of convergence against which extratextual divergence can be measured. The value of the computational layer, in this design, is partly to license a negative result, namely that translations converge, that makes the positive result about fatwa legible.")
para("Substantively, the typology contributes to the political economy of Islamic finance a comparative, scripturally anchored frame. Where Rudnyckyj (2019) reads Malaysia's finance jurisprudence as a developmental project, we place that project on a regional spectrum whose poles are Malaysia's industry accommodation and Indonesia's principled prohibition, with Singapore's minority necessity and Brunei's monarchical institutionalization as distinct logics between them. The spectrum is consistent with accounts that read Islamic finance as reproducing, rather than replacing, the conventional order (Rethel 2011; El-Gamal 2006), and with readings of the Council of Indonesian Ulama as an increasingly assertive guardian of orthodoxy (van Bruinessen 2013). For translation studies, the Q 83:1 close reading offers a compact case of domestication (Venuti 2008; Baker 2018): the receiving language's resources and social context reshape a commercial-ethics verse, and do so more strongly in a minority-language edition than in the majority-language state editions.")
para("The findings also speak to policy. State translation and state fatwa are produced by overlapping but not identical institutions, and the divergence between them is not a failure of coordination but a structural feature: scripture is standardized for a national readership while rulings are tuned to national economic conditions. Recognizing the two layers as distinct helps explain why debates over Islamic economics in the region are rarely debates over the text.")
para("Finally, the design has a payoff for digital Qurʾān studies. Much computational work on the Qurʾān has concentrated on the Arabic text and its classical commentary; the vernacular translations that most Muslims actually read have received far less attention, in part because they are multilingual and resist a single-language pipeline. Anchoring on the invariant Arabic and comparing renderings through language-agnostic embeddings offers one general recipe for studying translated scripture at scale, applicable well beyond Southeast Asia, to the many national Qurʾān editions produced across the Muslim world, and to the comparison of successive revisions of a single national edition over time.")
para("How far does the pattern generalize? The design is portable in principle to any setting where a single scriptural source is rendered into multiple authoritative editions and where religious institutions issue economic rulings. The Arab world, South Asia, and the Turkic-speaking states each present national Qurʾān editions and distinct fatwa regimes, and the same two-layer method could ask there whether translation converges while ruling diverges, or whether the two move together. The Southeast Asian answer, that they come apart, may not hold elsewhere, and establishing that would require the comparison. What travels is the method: anchor on the invariant source, measure the translation layer computationally, and set it against a coded reading of the juridical layer.")
para("The two-layer result also cautions against a common inference in the study of Islamic economics, namely reading a state's scriptural translation as a guide to its economic jurisprudence. In Southeast Asia the inference fails: the most textually similar pair of editions, Malaysia and Brunei, anchors the two ends of a shared conservatism whose fatwa expressions nonetheless diverge. Analysts who want to know how a state will treat interest, insurance, or a novel instrument such as cryptocurrency will learn more from its financial-institutional configuration than from its Qurʾān edition. The text sets the shared vocabulary of debate; the institution decides the ruling.")
para("For the study of Islam in Southeast Asia specifically, the article offers a method for comparing national religious outputs at scale, one that neither flattens the region into a single case nor treats each country in isolation. The five editions are related but distinct, and the method makes their relations measurable. Area-studies scholarship has long described the family resemblance among the region's Islamic institutions; here that resemblance is quantified, and its limits, the points where family resemblance gives way to national divergence, are located precisely.")
para("Two extensions suggest themselves. The first is diachronic: the Indonesian edition has passed through several official revisions, and the same embedding method would measure how its rendering of the muʿāmalāt verses has drifted across editions, turning a synchronic comparison into a history of a single national text. The second is to close the loop on mechanism by mining the fatwa texts themselves, coding the rationales they cite and testing directly whether economic-institutional considerations appear more often, and more decisively, in the more permissive regimes. Both would strengthen the causal reading that the present design can only gesture toward.")

# ============================ 8. LIMITATIONS ============================
h1("8. Limitations")
para("Four limitations bound the claims. First, the corpus is one of standardized editions, and two of the five, the Thai and Tagalog Rowwad texts, are not state-authored in the way the Indonesian, Malay, and Brunei editions are; the national-edition framing is therefore uneven, and the strongest institutional comparisons are the three Malay-language state editions. Second, cross-lingual similarity conflates linguistic and interpretive distance, so the low Thai and Tagalog scores must not be read as doctrinal difference; the interpretive signal lies in the cognate editions and in close reading. Third, the fatwa comparison rests on four issues and four regimes, so the linkage is comparative and interpretive, not a statistical correlation. Several cells rest on institutional inference or on regulatory advisories rather than located issue-specific fatwas, and are marked as such in Figure 6 and the codebook, with no claim resting on them alone. The four issues were chosen for their contrast, which risks confirmation bias toward divergence, and the strictness scores are a coded rubric whose inter-coder reliability should be established with Cohen's kappa before publication. Fourth, Thailand and the Philippines are absent from the fatwa layer not by oversight but because their muʿāmalāt fatwa infrastructure is thin, an asymmetry that is itself a finding about the uneven institutionalization of Islamic economic authority, and a caution against treating the five editions as five comparable states.")
para("A fifth caveat concerns the embedding model itself. LaBSE encodes meaning as learned from general parallel corpora, not from religious language, and it may under-represent the theological connotations that matter most to exegetes. A term that is near-synonymous in everyday usage may carry a decisive doctrinal charge that the model does not register. This is a reason to treat the cross-lingual scores as a coarse instrument, useful for ranking and for establishing the convergence baseline, and to place the interpretive weight on the close readings, where a human reader can see what the model cannot.")

# ============================ 9. CONCLUSION ============================
h1("9. Conclusion")
para("Southeast Asia's state and state-adjacent Qurʾān editions render the verses of economic life in strikingly similar terms. Their translations form a shared, conservative substrate, clustered by language family and diverging only in a handful of ethically abstract verses. Yet the same states' fatwas on interest, insurance, cryptocurrency, and tawarruq diverge sharply, and the ordering of that divergence, with Malaysia most permissive and Indonesia strictest, tracks not anything in their translations but each state's economic-institutional position. Translation is the region's layer of convergence; fatwa is where its political economy asserts itself. Methodologically, the study shows that distant reading can be carried across the boundary that has limited it, from one language into a genuinely multilingual corpus, by anchoring on the invariant source text and letting semantic embeddings do the comparing. The larger lesson, for the study of Islamic economics in Southeast Asia, is that the action is rarely in the text and usually in the ruling.")
para("The method invites replication and correction. The corpus, the code, and the fatwa codebook are open, and every claim in the quantitative layer can be recomputed while every cell in the juridical layer can be contested against its cited source. That openness is deliberate. A study that argues the interesting variation lies in institutions rather than in texts should make its own institutional apparatus, its data and its coding decisions, as inspectable as the scriptures it compares.")

# ============================ BACK MATTER ============================
h1("Data and Code Availability")
para("The verse corpus, the coded fatwa table and codebook, and all analysis scripts (Python for corpus assembly and natural-language processing; R for figures, statistics, and tables) are available in the project repository. Translation texts derive from open repositories: QuranEnc (quranenc.com), the Quran.com application-programming interface (api.quran.com), and the official Mushaf Brunei application.")
h1("Disclosures")
para("Ethics: the study uses published translations and public fatwa documents; no human subjects were involved. Artificial-intelligence use: computational analysis used open-source libraries, and generative-AI assistance was used for drafting support and is disclosed here. Conflict of interest: none declared. Funding: to be completed.")

# ============================ REFERENCES (APSA, 47 entries) ============================
h1("References")
refs = [
 "Accounting and Auditing Organization for Islamic Financial Institutions (AAOIFI). 2010. Shariʿah Standards. Manama: AAOIFI. https://aaoifi.com",
 "Azra, Azyumardi. 2004. The Origins of Islamic Reformism in Southeast Asia: Networks of Malay-Indonesian and Middle Eastern ‘Ulamā’ in the Seventeenth and Eighteenth Centuries. Honolulu: University of Hawai‘i Press. ISBN 9780824828486.",
 "Baker, Mona. 2018. In Other Words: A Coursebook on Translation. 3rd ed. London: Routledge. https://doi.org/10.4324/9781315619187",
 "Bank Negara Malaysia, Shariah Advisory Council. 2010. Resolutions on Tawarruq and Bursa Suq al-Sila. Kuala Lumpur: Bank Negara Malaysia. https://www.bnm.gov.my/islamic-banking-takaful",
 "Blei, David M., Andrew Y. Ng, and Michael I. Jordan. 2003. Latent Dirichlet Allocation. Journal of Machine Learning Research 3: 993–1022. https://jmlr.org/papers/v3/blei03a.html",
 "Bowen, John R. 2003. Islam, Law, and Equality in Indonesia: An Anthropology of Public Reasoning. Cambridge: Cambridge University Press. ISBN 9780521531894.",
 "Brunei Darussalam Central Bank (BDCB). 2017. Public Advisory on Cryptocurrencies. Bandar Seri Begawan: BDCB. https://www.bdcb.gov.bn",
 "Bruinessen, Martin van, ed. 2013. Contemporary Developments in Indonesian Islam: Explaining the ‘Conservative Turn’. Singapore: ISEAS. https://doi.org/10.1355/9789814414579",
 "Devlin, Jacob, Ming-Wei Chang, Kenton Lee, and Kristina Toutanova. 2019. BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding. In Proceedings of NAACL-HLT 2019, 4171–4186. https://doi.org/10.18653/v1/N19-1423",
 "Dewan Syariah Nasional–MUI (DSN-MUI). 2001. Fatwa No. 21/DSN-MUI/X/2001 tentang Pedoman Umum Asuransi Syariah. Jakarta: DSN-MUI. https://dsnmui.or.id",
 "Dewan Syariah Nasional–MUI (DSN-MUI). 2011. Fatwa No. 82/DSN-MUI/VIII/2011 tentang Perdagangan Komoditi Berdasarkan Prinsip Syariah di Bursa Komoditi. Jakarta: DSN-MUI. https://dsnmui.or.id",
 "El-Gamal, Mahmoud A. 2006. Islamic Finance: Law, Economics, and Practice. Cambridge: Cambridge University Press. ISBN 9780521864145.",
 "Feener, R. Michael. 2013. Shariʿa and Social Engineering: The Implementation of Islamic Law in Contemporary Aceh, Indonesia. Oxford: Oxford University Press. https://doi.org/10.1093/acprof:oso/9780199678846.001.0001",
 "Feng, Fangxiaoyu, Yinfei Yang, Daniel Cer, Naveen Arivazhagan, and Wei Wang. 2022. Language-agnostic BERT Sentence Embedding. In Proceedings of the 60th Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers), 878–891. https://doi.org/10.18653/v1/2022.acl-long.62",
 "Grootendorst, Maarten. 2022. BERTopic: Neural Topic Modeling with a Class-Based TF-IDF Procedure. arXiv:2203.05794. https://doi.org/10.48550/arXiv.2203.05794",
 "Hallaq, Wael B. 2009. Sharīʿa: Theory, Practice, Transformations. Cambridge: Cambridge University Press. ISBN 9780521678742.",
 "Hefner, Robert W. 2000. Civil Islam: Muslims and Democratization in Indonesia. Princeton: Princeton University Press. https://press.princeton.edu/books/paperback/9780691050478/civil-islam",
 "Hooker, M. B. 2003. Indonesian Islam: Social Change through Contemporary Fatawa. Honolulu: University of Hawai‘i Press. https://uhpress.hawaii.edu/title/indonesian-islam-social-change-through-contemporary-fatawa/",
 "Hosen, Nadirsyah. 2004. Behind the Scenes: Fatwas of Majelis Ulama Indonesia (1975–1998). Journal of Islamic Studies 15(2): 147–179. https://doi.org/10.1093/jis/15.2.147",
 "Ichwan, Moch Nur. 2013. Towards a Puritanical Moderate Islam: The Majelis Ulama Indonesia and the Politics of Religious Orthodoxy, in Contemporary Developments in Indonesian Islam, ed. Martin van Bruinessen, 60–104. Singapore: ISEAS.",
 "Johns, Anthony H. 1988. Qurʾānic Exegesis in the Malay World, in Approaches to the History of the Interpretation of the Qurʾān, ed. Andrew Rippin, 257–287. Oxford: Clarendon Press.",
 "Jockers, Matthew L. 2013. Macroanalysis: Digital Methods and Literary History. Urbana: University of Illinois Press. ISBN 9780252079078.",
 "Kaptein, Nico J. G. 2004. The Voice of the ʿUlamāʾ: Fatwas and Religious Authority in Indonesia. Archives de sciences sociales des religions 125: 115–130. https://doi.org/10.4000/assr.1038",
 "Kementerian Agama RI, Lajnah Pentashihan Mushaf al-Qurʾan. 2019. Al-Qurʾan dan Terjemahnya: Edisi Penyempurnaan 2019. Jakarta: Kementerian Agama RI. https://lajnah.kemenag.go.id",
 "Kuran, Timur. 2004. Islam and Mammon: The Economic Predicaments of Islamism. Princeton: Princeton University Press. https://press.princeton.edu/books/paperback/9780691126296/islam-and-mammon",
 "Lange, Christian, Maksim Abdul Latief, Yusuf Çelik, A. Melle Lyklema, Dafne E. van Kuppevelt, and Janneke van der Zwaan. 2021. Text Mining Islamic Law. Islamic Law and Society 28(3): 234–281. https://doi.org/10.1163/15685195-bja10009",
 "Masud, Muhammad Khalid, Brinkley Messick, and David S. Powers, eds. 1996. Islamic Legal Interpretation: Muftis and Their Fatwas. Cambridge, MA: Harvard University Press. ISBN 9780674468702.",
 "Majelis Ulama Indonesia (MUI). 2004. Fatwa No. 1/2004 tentang Bunga (Interest/Fāʾidah). Jakarta: MUI. https://mui.or.id/baca/fatwa/hukum-bunga-interestfaidah",
 "Majelis Ulama Indonesia (MUI). 2022. Fatwa No. 1/2022 tentang Hukum Uang Kripto (Cryptocurrency). Jakarta: MUI. https://mui.or.id",
 "Majlis Ugama Islam Singapura (MUIS), Office of the Mufti. 2010. Fatwa on Conventional Insurance and CPF Nomination. Singapore: MUIS. https://www.muis.gov.sg/officeofthemufti/Fatwa",
 "Moretti, Franco. 2013. Distant Reading. London: Verso. https://www.versobooks.com/en-gb/products/1421-distant-reading",
 "Mudzhar, Mohamad Atho. 1993. Fatwas of the Council of Indonesian Ulama: A Study of Islamic Legal Thought in Indonesia, 1975–1988. Jakarta: INIS.",
 "Muhanna, Elias, ed. 2016. The Digital Humanities and Islamic & Middle East Studies. Berlin: De Gruyter. https://doi.org/10.1515/9783110376517",
 "Nida, Eugene A. 1964. Toward a Science of Translating: With Special Reference to Principles and Procedures Involved in Bible Translating. Leiden: Brill. https://doi.org/10.1163/9789004495746",
 "OIC International Islamic Fiqh Academy. 2009. Resolution 179 (19/5) on Tawarruq. Jeddah: OIC Fiqh Academy. https://iifa-aifi.org/en/",
 "Pink, Johanna. 2019. Muslim Qurʾānic Interpretation Today: Media, Genealogies and Interpretive Communities. Sheffield: Equinox. https://www.equinoxpub.com/home/muslim-quranic-interpretation/",
 "Quran.com. 2023. Quran.com API v4 (translations). https://api.quran.com",
 "QuranEnc. 2023. Encyclopaedia of Qurʾan Translations (King Fahd Complex / Rowwad Translation Center). https://quranenc.com",
 "Reimers, Nils, and Iryna Gurevych. 2019. Sentence-BERT: Sentence Embeddings using Siamese BERT-Networks. In Proceedings of the 2019 Conference on Empirical Methods in Natural Language Processing (EMNLP-IJCNLP), 3982–3992. https://doi.org/10.18653/v1/D19-1410",
 "Rethel, Lena. 2011. Whose Legitimacy? Islamic Finance and the Global Financial Order. Review of International Political Economy 18(1): 75–98. https://doi.org/10.1080/09692290902983999",
 "Riddell, Peter G. 2001. Islam and the Malay-Indonesian World: Transmission and Responses. Honolulu: University of Hawai‘i Press. https://uhpress.hawaii.edu/title/islam-and-the-malay-indonesian-world-transmission-and-responses/",
 "Ricklefs, M. C. 2001. A History of Modern Indonesia since c.1200. 3rd ed. Basingstoke: Palgrave. ISBN 9780333801000.",
 "Rudnyckyj, Daromir. 2019. Beyond Debt: Islamic Experiments in Global Finance. Chicago: University of Chicago Press. https://doi.org/10.7208/chicago/9780226552118.001.0001",
 "Salim, Arskal. 2008. Challenging the Secular State: The Islamization of Law in Modern Indonesia. Honolulu: University of Hawai‘i Press. https://doi.org/10.21313/hawaii/9780824832377.001.0001",
 "Underwood, Ted. 2019. Distant Horizons: Digital Evidence and Literary Change. Chicago: University of Chicago Press. https://doi.org/10.7208/chicago/9780226612973.001.0001",
 "Venuti, Lawrence. 2008. The Translator's Invisibility: A History of Translation. 2nd ed. London: Routledge. https://doi.org/10.4324/9780203553190",
 "Warde, Ibrahim. 2010. Islamic Finance in the Global Economy. 2nd ed. Edinburgh: Edinburgh University Press. https://doi.org/10.1515/9780748631674",
 "Wilson, M. Brett. 2014. Translating the Qurʾan in an Age of Nationalism: Print Culture and Modern Islam in Turkey. Oxford: Oxford University Press. ISBN 9780198719434.",
 "Zadeh, Travis. 2012. The Vernacular Qurʾan: Translation and the Rise of Persian Exegesis. Oxford: Oxford University Press. ISBN 9780199670773.",
]
for r in refs:
    p = doc.add_paragraph(); run = p.add_run(r); run.font.size = Pt(11)
    p.paragraph_format.space_after = Pt(4)
    p.paragraph_format.left_indent = Inches(0.4); p.paragraph_format.first_line_indent = Inches(-0.4)

doc.save(OUT)
w = 0
for p in doc.paragraphs: w += len(re.findall(r"\S+", p.text))
for t in doc.tables:
    for row in t.rows:
        for c in row.cells: w += len(re.findall(r"\S+", c.text))
emdash = sum(p.text.count("—") for p in doc.paragraphs)
print("SAVED", OUT)
print("word count:", w, "| refs:", len(refs), "| em-dashes:", emdash, "| figures:", len(doc.inline_shapes), "| tables:", len(doc.tables))
